### ISSUE TITLE
Bug Report | www.

### ISSUE THREAD

**Issue by Mennaruuk** [spikecodes/libreddit#109]
**Describe the bug**
I have to manually remove www. from URL to access Libreddit's official instances.

**To reproduce**
1. Go to https://www.libreddit.spike.codes

**Expected behavior**
I think www. should redirect to the site without www. That way, people won't have to face an error. This isn't a huge issue for computer users (if users want to not touch Reddit.com, they can use [Privacy Redirect](https://github.com/SimonBrazell/privacy-redirect)), but it's a problem when I'm on Safari and I find a Reddit search. Unfortunately, iOS doesn't allow custom redirecting, so I'm left with manually selecting all of www.reddit.com, deleting it, and instead typing libredd.it.

**Additional context**
Is there a way to do something like this for libredd.it and libreddit.spikes.codes?
![image](https://user-images.githubusercontent.com/52135169/107296006-8a8dd680-6a3e-11eb-99e9-1ed0eaac51e0.png)

**Comment by stranger-danger-zamu** [comment]
Pretty sure this is more to do with which domains the HTTPS certificates were generated for (and partially how any reverse proxies being utilized are configured).

**Comment by fres7h** [comment]
> Pretty sure this is more to do with which domains the HTTPS certificates were generated for (and partially how any reverse proxies being utilized are configured).
> 
> 
> 
> 

i feel like this isn't an issue at all, and that adding a new cname and getting a new ssl cert for www.libreddit.spike.codes would too much trouble for such a non issue.

**Comment by Mennaruuk** [comment]
I’ll be closing this issue since I learned this actually could bring even more of a headache and costs to the project. Thanks for the feedback!

**Comment by Jonta** [comment]
Found this issue because I was going to report it myself

Removing it from the URL is tedious when switching back and forth, throws `SSL_ERROR_INTERNAL_ERROR_ALERT` and is to a new user

Hope it becomes feasible in future

**Comment by fres7h** [comment]
it's not an issue lol

**Comment by Jonta** [comment]
> it's not an issue lol

@fres7h How so?

**Comment by fres7h** [comment]
because adding a cname and getting a new ssl cert is quite a bit of trouble for something that so trivial. it seems to me you guys are just a bit lazy and can't be bothered to hit delete a few times. websites don't need to have a www subdomain, i don't know why so many people care about libreddit having one.

**Comment by Jonta** [comment]
> because adding a cname and getting a new ssl cert is quite a bit of trouble for something that so trivial. it seems to me you guys are just a bit lazy and can't be bothered to hit delete a few times. websites don't need to have a www subdomain, i don't know why so many people care about libreddit having one.

@fres7h

- You claim it's not an issue…
- …because, as you reiterate, it's a hassle to fix

Which does not follow. Something *can* be an issue, even though fixing it may not be worth it. It can become worth it in future. (And yes, I am aware of "it's not an issue" as a euphemism for "this issue is insignificant".)

- You state you don't understand what the problem is, but
- You guess that people are lazy

All while not capitalising the 1st letters of sentences. My hypothesis for that is also laziness (see below), as you do the same in your current profile text, where you don't even capitalise your first name. Even though your location is set to "united states", where English is the predominant language

Now, since your current profile text reads

> i know little to nothing about programming

and

> […] to do stuff i'm too lazy to do myself. 

A thing to know about programming is that it's collaborative. Especially in a place like this.

Sure: Unlike in many other fields, you can often demonstrate that your proposed solution is objectively superior. But how many people will be left to demonstrate such solutions, if you behave like that?

And what sorts of people will they be?

If you too are generous, others are more likely to be so to you. Which is good for the next time you get stuck, especially since you "know little to nothing about programming"

Programming is vast, and none of us will ever know everything.

To me right now, you're coming off as a brash newcomer who knows what a CNAME-record is, and wants to seem cool by demonstrating this knowledge, while putting other people down.

Is that the kind of people you want to surround yourself with? Who make fun of you when you have a problem they don't have?

That does not strike me as a great strategy for the marathons of life and programming.

On here, you're communicating with people of different ages, languages and experience levels.

So follow the https://en.wikipedia.org/wiki/Robustness_principle

<hr />

To "I don't know why this is an issue":

- Enter "reddit.com" into your address bar
- It redirects to "https://www.reddit.com"
- Go to a subreddit
- Then decide to view the subreddit on libreddit instead:
- Ctrl+L to get to the address bar
- "redd" -> "libredd"
- "it.com" -> ".it"
- Hit enter
- Wait
- Nope, doesn't work
- Get annoyed
- Ctrl+L
- Ctrl+arrowkeys
- Select "www."
- Backspace
- Enter

That's why this is an issue. Even after https://github.com/spikecodes/libreddit/issues/154 is fixed

**Comment by spikecodes** [comment]
Hey guys, GitHub Issues isn't the place for arguing but I can see how removing `www.` could be an annoyance.

Ideally I would redirect `www.libredd.it` to `libredd.it` using Cloudflare DNS but for that to Page Rules, I'd have to enable Cloudflare's reverse proxy which I don't want to do for privacy reasons.

Do you guys have any other ideas for redirecting a subdomain through DNS that wouldn't require building and hosting a new website to redirect using JS?

**Comment by fres7h** [comment]
i know next to something about programming, i just haven't updated my bio, as i selfhost my git stuff. 

anyways, when i say it's not an issue, i mean, it's not an issue at all. a large amount of websites have purposely chose to not use www. as it really just clutters up the url. 

this is a feature request, not an issue of any significance/importance. 

> > because adding a cname and getting a new ssl cert is quite a bit of trouble for something that so trivial. it seems to me you guys are just a bit lazy and can't be bothered to hit delete a few times. websites don't need to have a www subdomain, i don't know why so many people care about libreddit having one.
> 
> 
> 
> @fres7h
> 
> 
> 
> - You claim it's not an issue…
> 
> - …because, as you reiterate, it's a hassle to fix
> 
> 
> 
> Which does not follow. Something *can* be an issue, even though fixing it may not be worth it. It can become worth it in future. (And yes, I am aware of "it's not an issue" as a euphemism for "this issue is insignificant".)
> 
> 
> 
> - You state you don't understand what the problem is, but
> 
> - You guess that people are lazy
> 
> 
> 
> All while not capitalising the 1st letters of sentences. My hypothesis for that is also laziness (see below), as you do the same in your current profile text, where you don't even capitalise your first name. Even though your location is set to "united states", where English is the predominant language
> 
> 
> 
> Now, since your current profile text reads
> 
> 
> 
> > i know little to nothing about programming
> 
> 
> 
> and
> 
> 
> 
> > […] to do stuff i'm too lazy to do myself. 
> 
> 
> 
> A thing to know about programming is that it's collaborative. Especially in a place like this.
> 
> 
> 
> Sure: Unlike in many other fields, you can often demonstrate that your proposed solution is objectively superior. But how many people will be left to demonstrate such solutions, if you behave like that?
> 
> 
> 
> And what sorts of people will they be?
> 
> 
> 
> If you too are generous, others are more likely to be so to you. Which is good for the next time you get stuck, especially since you "know little to nothing about programming"
> 
> 
> 
> Programming is vast, and none of us will ever know everything.
> 
> 
> 
> To me right now, you're coming off as a brash newcomer who knows what a CNAME-record is, and wants to seem cool by demonstrating this knowledge, while putting other people down.
> 
> 
> 
> Is that the kind of people you want to surround yourself with? Who make fun of you when you have a problem they don't have?
> 
> 
> 
> That does not strike me as a great strategy for the marathons of life and programming.
> 
> 
> 
> On here, you're communicating with people of different ages, languages and experience levels.
> 
> 
> 
> So follow the https://en.wikipedia.org/wiki/Robustness_principle
> 
> 
> 
> <hr />
> 
> 
> 
> To "I don't know why this is an issue":
> 
> 
> 
> - Enter "reddit.com" into your address bar
> 
> - It redirects to "https://www.reddit.com"
> 
> - Go to a subreddit
> 
> - Then decide to view the subreddit on libreddit instead:
> 
> - Ctrl+L to get to the address bar
> 
> - "redd" -> "libredd"
> 
> - "it.com" -> ".it"
> 
> - Hit enter
> 
> - Wait
> 
> - Nope, doesn't work
> 
> - Get annoyed
> 
> - Ctrl+L
> 
> - Ctrl+arrowkeys
> 
> - Select "www."
> 
> - Backspace
> 
> - Enter
> 
> 
> 
> That's why this is an issue. Even after https://github.com/spikecodes/libreddit/issues/154 is fixed

**Comment by httpjamesm** [comment]
As a programmer, I can assure you this isn't an issue :)

**Comment by fres7h** [comment]
just host your own instance with a www. lol

**Comment by Jonta** [comment]
> As a programmer, I can assure you this isn't an issue :)

@httpjamesm This seems like an argument from authority

> just host your own instance with a [www](http://www). lol

@fres7h I think you'd agree this is not feasible for non-technical users

**Comment by fres7h** [comment]
Bro you're a Java programmer you should be fine

**Comment by fres7h** [comment]
Okay, listen, I'll add a WWW redirect to my two instances if you apologize for being mean ):
