### ISSUE TITLE
Feature Request | Add option on profile page to only show comments or posts

### ISSUE THREAD

**Issue by robrobinbin** [spikecodes/libreddit#119]
**Is your feature request related to a problem? Please describe.**
Reddit has the option to show either everything, posts or comments on a profile page. Libreddit is missing this option.

**Describe the solution you'd like**
Add option on profile page to only show comments or posts.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by KaKi87** [comment]
Hello,

Why was this issue closed as solved ?

Profile page only shows an "overview" tab which displays both posts and comments, as well as a "comments" tab, but no tab that only displays posts.

Thanks

**Comment by spikecodes** [comment]
Hi @KaKi87,

There is actually a "Submitted" tab as well but I think it got cut off on mobile due to incorrect styling. Just fixed this in https://github.com/libreddit/libreddit/commit/a4eecb251eba832f4d6b916286d51d3f786969d6 and changes will be viewable in the next release!

Thanks for reporting this.
