### ISSUE TITLE
Bug Report | For r/random, name of sidebar's subreddit is different than that of posts

### ISSUE THREAD

**Issue by Mennaruuk** [spikecodes/libreddit#133]
**Describe the bug**
It seems as if Libreddit is randomizing both the sidebar and posts so that the sidebar's subreddit is one thing, while the posts' subreddit is another.

**To reproduce**
1. Go to r/random
2. Check if sidebar's subreddit is same as posts' subreddit
![imageedit_1_3075327271](https://user-images.githubusercontent.com/52135169/108820268-f0737580-7589-11eb-8172-afd6145f5f01.png)

**Expected behavior**
Both should match.

**Additional context**
This also applies to r/randnsfw.

**Comment by spikecodes** [comment]
Thank you for this bug report! I haven't seen `r/random` before, this is interesting.

The issue seems to lie in the fact that Libreddit sends a separate request for subreddit posts and subreddit information. Each request to `r/random` redirects the client to a random subreddit so the sidebar and posts are being sent to two different subreddits as they are two different requests.
