### ISSUE TITLE
Few Opportunities (PageSpeed Insights)

### ISSUE THREAD

**Issue by bnainar** [spikecodes/libreddit#185]
![IMG_20210408_165846](https://user-images.githubusercontent.com/59839368/114019366-f00a1200-988b-11eb-87a8-a8a304e8e393.jpg)

What do you think about the 5 things it complains, and can we improve it?

Link: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Flibredd.it%2Fr%2Fislam%2Ftop%3Ft%3Dall

**Comment by spikecodes** [comment]
Thank you for reporting these useful statistics! I've addressed each of their described issues below:
1. Unfortunately, the images are served from Reddit as PNGs so unless Reddit changes their image sharing MIME type or Libreddit converts every image (would be an unnecessarily large load on the server), images cannot be served as the "next-gen" formats which Google Lighthouse describes.
2. The second warning is written with a typical web server in mind. Whereas Libreddit is proxying all requests through the backend so the longer server response time is to expected.
3. Text compression is a good idea! My HTTP server, Hyper, [does not have support for compression algorithms built-in](https://github.com/hyperium/hyper/discussions/2497) but I could add Brotli compression support through [this crate](https://github.com/dropbox/rust-brotli).
4. The network payload can be reduced by serving the image previews in "card mode" rather than the images. I've noticed this as well and I think I could fix it.
5. The caching policy is actually determined by Reddit and it is designed to allow for images to be taken down through moderation and not persist on client devices. Therefore, Libreddit proxies that cache policy when relaying media.

The points that I see as true issues and which could be improved upon are 3 and 4. I've opened #186 to tackle number three and  #187 for number four.
