### ISSUE TITLE
Wiki: HTML source is not rendered.

### ISSUE THREAD

**Issue by jtagcat** [spikecodes/libreddit#196]
https://r.c7.ee/r/datahoarder/wiki/Software

**Comment by spikecodes** [comment]
Thanks for this bug report! I'm trying to understand why this happens, I don't know how this wiki page specifically could be escaped. :thinking:

**Comment by grandeljay** [comment]
Could the HTML comment Tag be of any relevance? `<!-- SC_OFF -->` Maybe it's not rendered because it's a text/comment and not HTML.

**Comment by spikecodes** [comment]
I think it must be something to do with Libreddit's rendering method considering [the other pages](https://libredd.it/r/datahoarder/wiki/) also have that comment but the comment's tags, as you mentioned, aren't escaped in other pages like they are in this one.

**Comment by spikecodes** [comment]
Happens in some search feeds too: https://libredd.it/r/rust/search?q=Vec&restrict_sr=on&sort=relevance&t=all

**Comment by joshers** [comment]
Jinja automatically escapes HTML elements when rendering variables. If you wish to allow the raw HTML to be parsed normally, the "safe" selector needs to be included with the variable:

`{{ wiki | safe }}`

Now, this opens up the potential for nasties to sneak by, so there should probably be some escaping done on the backend for things like javascript.

**Comment by joshers** [comment]
Ignore above, I mistakenly thought Jinja was being used (sorry, Python/Flask are what I'm most familiar with) and was behaving bizarrely.

As specifically related to this wiki problem, the issue is that the link on the main Datahoarder page has a capitalized "S", while the _actual_ wiki page does not. So when libreddit tries to grab the json for /wiki/Software, it gets redirected via 304 to /wiki/software. What is important here, is that the redirect does not preserve the GET variables, so raw_json is not set to one anymore, and the content_html that is returned is already escaped by the reddit API.

**Comment by spikecodes** [comment]
@joshers Thanks so much for troubleshooting this!
