### ISSUE TITLE
Support viewing quarantined subreddits

### ISSUE THREAD

**Issue by onebyte4** [spikecodes/libreddit#208]
## Is your feature request related to a problem? Please describe.
Quarantined Subreddits Cant Viewable like (example : r/fullcommunism)

## Describe the solution you'd like
Support Quarantined Subreddits

## Describe alternatives you've considered
in old.reddit.com some quarantined subreddits viewable without login/email verification

**Comment by curlpipe** [comment]
Had a little investigation and found this.

https://old.reddit.com/r/FULLCOMMUNISM/about.json

which happily provides data. vs using the reddit.com request

Perhaps a solution to this is to use old.reddit.com exclusively to access all subreddits.

otherwise, we could create a priority kinda thing where it tries with reddit.com, then it tries with old.reddit.com if the sub couldn't be accessed?
