### ISSUE TITLE
Code blocks in markdown occasionally don't render

### ISSUE THREAD

**Issue by curlpipe** [spikecodes/libreddit#218]
## Describe the bug

Libreddit sometimes doesn't correctly render code blocks

![image](https://user-images.githubusercontent.com/11898833/117518644-82d7c280-af98-11eb-85fc-b01c42f36d62.png)

This is hideous.

## To reproduce
Compare 
https://libredd.it/r/rust/comments/n795ew/trouble_figuring_out_how_to_handle_client_server/
to 
https://reddit.com/r/rust/comments/n795ew/trouble_figuring_out_how_to_handle_client_server/

Reddit can render it, libreddit makes a meal of it.

## Expected behavior

To render the code block correctly.

## Additional context

Perhaps this is an issue with the reddit API. Potentially, it might be better to read in the raw markdown and use a library like `comrak` to convert it to html on the fly? Maybe it's an easier fix than that.

**Comment by spikecodes** [comment]
Thanks for opening this PR! Oddly, Reddit renders that as a code block on desktop yet not on the mobile website (see image below). Reddit has it's own [flavor of markdown](https://libredd.it/wiki/markdown#wiki_code_blocks_and_inline_code) that [differs from Commonmark and GFM](https://libredd.it/wiki/markdown#wiki_differences_from_commonmark_.2F_gfm) and appears to require a newline before the three backticks (\`) of a code block. As you mentioned, the HTML rendering in the API also does not designate that as a code block. Therefore, I believe it is Reddit's desktop website that is wrongly (meaning: violating the Reddit-flavored markdown specification) rendering that body of text as a code block, rather than a Libreddit issue.

![image](https://user-images.githubusercontent.com/19519553/117557840-e03a4500-b066-11eb-822e-a744e198b4f9.png)

**Comment by curlpipe** [comment]
So what can we do about this? Perhaps we could communicate with Reddit somehow?

**Comment by curlpipe** [comment]
I've tried looking around and I can only find the codebase for the older parser.

https://github.com/reddit/snudown

There is very little mention of the new parser. It probably isn't open source :///

**Comment by spikecodes** [comment]
The issue seems to only happen when the Reddit post includes ` ``` ` (which denotes the start of the markdown block) in the same line as regular text. Do you see this issue often enough to disable auto-redirect?

**Comment by caincodes** [comment]
I mean, it's not just a visual issue -- it completely removes code formatting as well, so I'm then unable to read nor copy the snippet. I had set up a url rewriter for reddit -> libreddit, but yeah I'd have to disable auto-redirect (at least temporarily) in order to view the properly formatted text.

Anyway, I haven't read through the libreddit source code so I can't say it'd be an easy bug to fix, but I'd say it's a large enough issue to consider a more "hacky" approach to solving, if necessary.

**Comment by kaspar030** [comment]
Came to report the same, found this issue, but unfortunately closed without fix. :(
