### ISSUE TITLE
Question: Use reddit account subscriptions?

### ISSUE THREAD

**Issue by mizzunet** [spikecodes/libreddit#229]
libreddit can't login with Reddit account for subscriptions, right? 
So, Is there anyway to use my account subscriptions data? 
For Indvidious, had an option for upload YouTube subscription.json which exported form YouTube itself

**Comment by spikecodes** [comment]
Correct, Libreddit doesn't support Reddit accounts and that feature is not planned either. Though, you can import subscriptions from Reddit pretty easily:

1. Visit https://www.reddit.com/subreddits and copy the "Multireddit of your subscriptions" link
2. Visit the multireddit link, replacing `reddit.com` with `libredd.it` (or your instance of choice)
3. Click the "Subscribe to Multireddit" button and you're all set!

Hope this helps! :)

**Comment by mizzunet** [comment]
Great, thank you (:

**Comment by spikecodes** [comment]
My pleasure! I've created [a Wiki page](https://github.com/spikecodes/libreddit/wiki/How-to-import-Reddit-subscriptions%3F) so new users will be able to find this information more easily.

**Comment by grandeljay** [comment]
Is there a particular reason it is not planned?

This project is a light in the dark for me, the Reddit desktop website is unusable and this is the only maintained Reddit desktop frontend I could find. Thanks for it btw!

Personally I'm hoping it will replace the Reddit website as we know it (including account subscriptions)

**Comment by spikecodes** [comment]
I'm really glad that you like Libreddit! :)

> Is there a particular reason it is not planned?

The primary reason is the code reworking that adding accounts would require. I may do it eventually but it's currently not planned. Also, I know that it's optional, but I feel that logging into a Reddit account over Libreddit would largely void that privacy Libreddit strives to offer.

> Personally I'm hoping it will replace the Reddit website as we know it (including account subscriptions)

I'm not sure if you're aware but you can [import your subscriptions from Reddit into Libreddit](https://github.com/spikecodes/libreddit/wiki/Import-Reddit-Subscriptions).

**Comment by Aloso** [comment]
> I'm not sure if you're aware but you can import your subscriptions from Reddit into Libreddit.

@spikecodes This is a nice feature, but it only achieves _part_ of the what a Reddit account offers. For instance, it doesn't allow upvoting posts or writing comments. Should I open a new issue for this? Also, would you accept PRs to add a login functionality? I don't think that this would negatively impact privacy, since logging in would be voluntary: Users can choose to not login. And even when logged in, privacy would be better than in the official Reddit website, which includes god knows how many trackers.

**Comment by Cwpute** [comment]
> Should I open a new issue for this? Also, would you accept PRs to add a login functionality?

You could always fork the project to allow login into a reddit account in your own branch, if that isn't what the maintainers want for their own :shrug:

**Comment by jaimehrubiks** [comment]
I can't find the import multireddit subscriptions button anywhere in the Ui

**Comment by wjk4** [comment]
It seems like this doesn't work anymore since it just throws me a "Hmm... We couldn't reach this Repl" error.

**Comment by spikecodes** [comment]
> It seems like this doesn't work anymore since it just throws me a "Hmm... We couldn't reach this Repl" error.

I believe that was a temporary outage. Should fix itself if you force refresh (Control+Shift+R or Control+F5).

**Comment by spikecodes** [comment]
> I can't find the import multireddit subscriptions button anywhere in the Ui

Here's a guide in the Wiki: https://github.com/libreddit/libreddit/wiki/Import-Reddit-Subscriptions

**Comment by itsthejb** [comment]
I hadn't known about this feature, so very happy to find out about it!

However, as an extension to this prob, I opened https://github.com/libreddit/libreddit/issues/562 a while ago. I wondering if there's anyway to recreate this using the iOS homescreen web app feature. Otherwise the app works great, but there's no way to import subscriptions, since by design this doesn't give you access to the URL bar...

Unless there's some trick? It would be great to be able to paste the URL somewhere in the libReddit UI

**Comment by KejjRod** [comment]
Great that you can import them, but it seems like it is capped. I could only import 31 subreddits but I follow 202. 

Might it be a limit on how many subreddits Reddit there can be in the link for the multireddit of my subscriptions?
