### ISSUE TITLE
Account Removal Request

### ISSUE THREAD

**Issue by i-am-cal** [spikecodes/libreddit#268]
Hi! Please can you remove the following account off libreddit, as it's my private Reddit account and has been appearing on Google and other places I don't want it to be.

u/cal6541

Thank you.

**Comment by TheCultLeader666** [comment]
Or maybe just block search engine crawlers from indexing user accounts. (Or just block them all together)

**Comment by i-am-cal** [comment]
How am i meant to do that?

**Comment by TheCultLeader666** [comment]
I was just suggesting solutions to the general problem of search engines indexing users. It was not directed at you @i-am-cal

**Comment by i-am-cal** [comment]
Final warning - or ill GDPR takedown this repo via GitHub for not complying with the Data Protection Act

**Comment by spikecodes** [comment]
Sorry for the late response. I agree with @TheCultLeader666 that adding a custom `robots.txt` (see #265) would allow people who host Libreddit to hide certain pages from showing up in Google results. Because Libreddit is hosted by so many people, I'm not able to prevent their website (specifically `libreddit.domain/u/cal6541`) from showing in search engines so you'd have to contact them individually regarding that. For the two official instances though, I can edit the `robots.txt` file (this is the file that tells search engines what sites they can crawl) hide user profiles by default. I'm also working on implementing #265 so that hosters will have more customization over this.

**Comment by spikecodes** [comment]
I just published [v0.15.1](https://github.com/spikecodes/libreddit/releases/tag/v0.15.1) which will hide all user profiles (on the official and the unofficial updated instances), including yours, from showing in search engine results once those search engines update their cache.

> ill GDPR takedown this repo via GitHub for not complying with the Data Protection Act, its took way too fucking long
Under Article 12.3 of the GDPR, I have 30 days to take action. I recognize that my response time was not ideal but it is well within the limit to not be considered a GDPR violation.
