### ISSUE TITLE
Libreddit API

### ISSUE THREAD

**Issue by pluja** [spikecodes/libreddit#291]
Does Libreddit have a public API? If so, is it documented somewhere?

**Comment by spikecodes** [comment]
Hey Pluja! Libreddit doesn't have an API because most of Libreddit's benefits come from the web interface (faster speeds, no ads, less resources loaded, etc.) so there really wouldn't be any advantage to using a Libreddit API over a proxied Reddit API. If you do need a something of that nature, I'd recommend taking a look at [Teddit's API](https://codeberg.org/teddit/teddit/wiki#teddit-api).

I've received [some requests](https://github.com/spikecodes/libreddit/issues/27) for adding APIs or RSS feeds so I'll add this response to [Libreddit's FAQ](https://github.com/spikecodes/libreddit/wiki/Frequently-Asked-Questions).
