### ISSUE TITLE
Feature Request | Hide Bots comment by default

### ISSUE THREAD

**Issue by somedevreally** [spikecodes/libreddit#306]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
Most of the subreddit uses bots to comment warning/rules/useless info, can this be disabled?
for example [u_AutoModerator](https://reddit.com/r/u_AutoModerator)

## Describe alternatives you've considered
if bot comments can to hidden

## Additional context
its waste of space too

![image](https://user-images.githubusercontent.com/26795436/138802119-a67e13ee-c61b-4c46-8b1d-b0b1b90cd80a.png)

**Comment by mikupls** [comment]
Idea (not sure if this was mentioned before):
I think usually the problem we face here is a *stickied* comment by a bot (i.e. the top comment space is "wasted"). From what I have personally seen, that "bot" account is also a "moderator" of the sub (I assume to get sticky powers and/or for visibility).

As such, to me it seems like the most scalable solution would be to auto-collapse stickied moderator comments. (Scalable because we are not hard-coding any user-names, or otherwise try to detect who is/ is not a bot)

Any thoughts? Would this fit everyone's use-case?

As an example, I was just now looking at `https://www.reddit.com/r/LifeProTips/comments/qvddd3/lpt_stop_thinking_about_whos_fault_is_it_start/`

---

Counter-point: On rare occasions I have seen mods e.g. manually locking down a thread for reasons, and justifying this in a stickied comment. In such cases, a libreddit user might miss this. I believe though that usually this is not done by the "bot" user, so it would be possible to distinguish this case by seeing a "normal" username in the collapsed top comment.

**Comment by spikecodes** [comment]
Sounds like a great alternative solution, thanks for your input!

I agree about the counterpoint but thread locking happens so rarely that I don't think Libreddit would need to have an exception coded in.
