### ISSUE TITLE
Support for riscv64?

### ISSUE THREAD

**Issue by sdanfa** [spikecodes/libreddit#319]
Hi,
I'm trying to build libreddit for riscv platform but I'm getting error with ring package. Ring package has been updated to work with riscv with this repo (https://github.com/OkitaSan/ring/tree/rv64gc-support). I'm trying to use that package but rust pulls older version anyway. I added the dependency to Cargo.toml as a build dependency here: "ring = { path = "../ring" }"

I'm getting the following error:
ubuntu@ubuntu:~/libreddit$ cargo run --target riscv64gc-unknown-linux-gnu
    Updating crates.io index
   Compiling ring v0.16.20
   Compiling indexmap v1.7.0
   Compiling futures-channel v0.3.17
   Compiling mio v0.7.14
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/home/ubuntu/libreddit/target/debug/build/ring-944b5679dbbc0ef5/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:358:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by spikecodes** [comment]
Yeah, I was able to reproduce your error and I think you're right that Rust is incorrectly pulling the older ring version. So from what I can tell, this is an issue with the compiler rather than Libreddit so I'll be closing this issue for now. Please let me know if you get cargo working and need assistance with building this project.

Thanks!
