### ISSUE TITLE
libreddit binary self-updating?

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [spikecodes/libreddit#343]
## Describe the implementation into Libreddit
maybe add a little sh script to scrap github each 3 days or so and if there new tag, it downloads new update

## Additional context
I used to use docker image but for some reason i keep hitting by this bad DNS is bad message and now i have no option but use binary of libreddit (it's good do not get me wrong) but it's bad when i need to visit github daily to check for updates

**Comment by spikecodes** [comment]
Hello,

None of the Libreddit deployment methods except for Replit and Glitch are self-updating. This is done so that Libreddit is as small as possible and people can use their preferred 3rd-party updating software.

Here's the self-updating bash script that I wrote for Glitch:
```bash
wget -O libreddit https://github.com/spikecodes/libreddit/releases/latest/download/libreddit
chmod +x libreddit
./libreddit -H 63115200
```
Whenever you wake up the Glitch instance, Glitch will grab the newest version from GitHub releases so you're always updated.

Hope this helps!
