### ISSUE TITLE
libreddit question

### ISSUE THREAD

**Issue by bihlink** [spikecodes/libreddit#392]
Hello. I have installed libreddit on repl.it = https://www.abid.cc
I am interested how i can change / edit templates on repl.it/ Need to edit meta tags to match my website and maybe logo too. I tried to edit files and re-run script but changes don't appear while i can see it saved in editor.

Can you help please

**Comment by spikecodes** [comment]
Hello, I see why this is happening. I created the `.replit` file to tell Repl.it to always down Libreddit from GitHub releases, mainly because that is much faster than building from source using Rust.

If you'd like to have Libreddit re-run with your changes, simply edit the `.replit` file to:
```bash
run = "cargo run"
language = "rust"
```

Though, this will take a very long time to run because Rust builds quite slowly inside Repl.it. Let me know if you have any other questions!
