### ISSUE TITLE
PSA: new fork, contributors wanted

### ISSUE THREAD

**Issue by Daniel-Valentine** [spikecodes/libreddit#594]
@PAI5REECHO and I started a fork, [libbacon/libbacon](https://github.com/libbacon/libbacon), in response to the stasis of the libreddit project (see #585). Contributors are wanted. Please raise new issues/PRs, especially if you have ones in this repo. Hopefully we can breathe life into this project once again.

@spikecodes: Thank you once again for building libreddit. Please let us know when you are back, and if you would like us to synchronize the fork against libreddit.

**Comment by sigaloid** [comment]
Hi, I'm unable to submit my pull request to the fork as I am a member of the org with no push access. I can't do a PR because my fork is a fork of this repo, not the new one, and deleting it would delete the current PR here. And apparently I can't fork the libbacon repo as you can only have one fork of a base repo and libbacon is a fork of this one.

PS: I'd be willing to contribute something that would auto-update the [instance list repo](https://github.com/libbacon/libreddit-instances) - a simple script/Rust program that checks for online availability and commits and pushes it, so that the libredirect addon et al can use it by accessing the JSON. fly.io has a quite generous free plan and would definitely fit on it.

I am happy to be invited and I'm willing to hopefully review/contribute as possible :)

**Comment by spikecodes** [comment]
Hi all! I apologize for my absence but am back now and will be supporting Libreddit's transition, as best I can, to a community-run project so my absences won't stall growth going forward.

I'd be interested in merging Ferrit back into Libreddit. Read my full update [here](https://github.com/spikecodes/libreddit/issues/599#issuecomment-1297851595).
